# AI配置
AI:
  baseUrl: https://qianfan.baidubce.com/v2
  apiKey: bce-v3/ALTAK-gxmbLJQhX9iD4p6OGMIy7/8f62c4050c143ae08c40d25affdae4751cf27d82
  modelName: deepseek-v3

# 目录配置
directory:
  source: /Users/faith/Music/source
  target: /Users/faith/Music/target

# 整理配置
mover:
  # 是否启用整理
  enabled: true
  # 命名模板 title: 标题 performers: 艺术家 albumArtists: 专辑艺术家 album: 专辑 year: 年份 disc: 碟片号 track: 曲目号
  namingTemplate: "{performers}/{album}/{track}.{title}{extension}"
  # 是否启用重命名
  rename: true
  # 整理方式 copy 复制，move 移动
  type: copy
